import static org.junit.Assert.assertEquals;

import java.io.IOException;
import java.security.NoSuchAlgorithmException;

import javax.crypto.KeyGenerator;
import javax.crypto.SecretKey;

import org.junit.Test;
import org.web3j.crypto.CipherException;
import org.web3j.crypto.Credentials;
import org.web3j.crypto.WalletUtils;

import xyz.reticulate.cryto.KeyStore;
import xyz.reticulate.exception.KeyException;
import xyz.reticulate.file.EncryptedFileBlock;
import xyz.reticulate.file.FileBlock;

public class ReticulateTests {
	
	/**
	 * Generate an aes key.
	 * @return An AES key.
	 * @throws NoSuchAlgorithmException
	 */
	public static SecretKey buildAESKey() throws NoSuchAlgorithmException {
		KeyGenerator keyGen = KeyGenerator.getInstance("AES");
		keyGen.init(256); // for example
		return keyGen.generateKey();
    }
	
	@Test
	public void createKeyStore() {
		KeyStore ks = new KeyStore(KeyStore.buildRSAKeyPair());
	}
	
	@Test
	public void loadEthereumWallet() throws IOException, CipherException {
		Credentials credentials = WalletUtils.loadCredentials("password", "wallet.json");
		KeyStore ks = new KeyStore(KeyStore.buildRSAKeyPairFromWallet(credentials));
	}
	
	/**
	 * Test that readnomly generated keys can encrypt and decrypt data.
	 * @throws KeyException
	 * @throws NoSuchAlgorithmException
	 */
	@Test
	public void encryptDecrypt() throws KeyException, NoSuchAlgorithmException {
		KeyStore ks = new KeyStore(KeyStore.buildRSAKeyPair());
		
		byte[] testData = {0, 1, 2, 3, 4};
		
		FileBlock block = new FileBlock(testData, 0);
		block.setKey(buildAESKey());
		
		EncryptedFileBlock encrypted = ks.encrypt(block);
		
		FileBlock result = ks.decrypt(encrypted);
		
		for (int i = 0; i < testData.length; i++) {
			assertEquals(testData[i], result.getContent()[i]);
		}
	}
	
	/**
	 * Test that keys built with a wallet can succesfully encrypt and then decrypt some data.
	 * @throws KeyException
	 * @throws NoSuchAlgorithmException
	 * @throws IOException
	 * @throws CipherException
	 */
	@Test
	public void encryptDecryptWallet() throws KeyException, NoSuchAlgorithmException, IOException, CipherException {
		Credentials credentials = WalletUtils.loadCredentials("password", "wallet.json");
		KeyStore ks = new KeyStore(KeyStore.buildRSAKeyPairFromWallet(credentials));
		
		byte[] testData = {0, 1, 2, 3, 4};
		
		FileBlock block = new FileBlock(testData, 0);
		block.setKey(buildAESKey());
		
		EncryptedFileBlock encrypted = ks.encrypt(block);
		
		FileBlock result = ks.decrypt(encrypted);
		
		for (int i = 0; i < testData.length; i++) {
			assertEquals(testData[i], result.getContent()[i]);
		}
	}
	
	/**
	 * Test that when a wallet is used to generate keys that another keystore generated by the same wallet can decrypt any data.
	 * @throws KeyException
	 * @throws NoSuchAlgorithmException
	 * @throws IOException
	 * @throws CipherException
	 */
	@Test
	public void encryptDecryptSeperateWallets() throws KeyException, NoSuchAlgorithmException, IOException, CipherException {
		Credentials credentials = WalletUtils.loadCredentials("password", "wallet.json");
		KeyStore ks1 = new KeyStore(KeyStore.buildRSAKeyPairFromWallet(credentials));
		
		Credentials credentials2 = WalletUtils.loadCredentials("password", "wallet.json");
		KeyStore ks2 = new KeyStore(KeyStore.buildRSAKeyPairFromWallet(credentials2));
		
		byte[] testData = {0, 1, 2, 3, 4};
		
		FileBlock block = new FileBlock(testData, 0);
		block.setKey(buildAESKey());
		
		EncryptedFileBlock encrypted = ks1.encrypt(block);
		
		FileBlock result = ks2.decrypt(encrypted);
		
		for (int i = 0; i < testData.length; i++) {
			assertEquals(testData[i], result.getContent()[i]);
		}
	}

}
